### ISSUE TITLE
NoClassDefFoundError: javax/xml/bind/JAXB

### ISSUE THREAD

**Issue by tiramon** [jmerle/cg-local-app#1]
I just downloaded the app and when i start it with `java -jar "CG Local.jar"` i get the following exception

> Exception in thread "FXLauncher-Thread" java.lang.NoClassDefFoundError: javax/xml/bind/JAXB
>         at fxlauncher.AbstractLauncher.syncManifest(AbstractLauncher.java:210)
>         at fxlauncher.AbstractLauncher.updateManifest(AbstractLauncher.java:92)
>         at fxlauncher.Launcher.lambda$start$0(Launcher.java:137)
>         at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXB
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
>         at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
>         ... 4 more

And the application freezes with spinning dots

**Comment by jmerle** [comment]
Hmm, that's weird. What Java distribution and version (the output of `java -version` will do) are you using?

Update 1:
Another bug was recently [issued](https://forum.codingame.com/t/cg-local/10359/2?u=jasperr) via the forums, which led me to the conclusion that CG Local doesn't work well with OpenJDK at the moment. Are you by any chance using OpenJDK?

Update 2:
The OpenJDK issue had to do with the fact that JavaFX is not included with OpenJDK by default. Since you already got the application to run, I don't think the two issues are related.

**Comment by jmerle** [comment]
Another bug was recently issues via the [forums](https://forum.codingame.com/t/cg-local/10359/3?u=jasperr), which led me to the conclusion that CG Local doesn't work well with OpenJDK at the moment. Are you by any chance using OpenJDK?

**Comment by tiramon** [comment]
Im using the default oracle jdk SE 1.8.0_73
For me this sounds like  a simple missing dependency

I just redownloaded the app from https://jaspervanmerle.com/cg-local/files/CG%20Local.jar and now i get a 'Error during Create Application phase' Dialog

> java.lang.ClassNotFoundException: com.jaspervanmerle.cglocal.CGLocal
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at fxlauncher.AbstractLauncher.createApplicationEnvironment(AbstractLauncher.java:170)
> 	at fxlauncher.Launcher.lambda$start$0(Launcher.java:149)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by jmerle** [comment]
What operating system are you using? There is an [open issue](https://github.com/edvin/fxlauncher/issues/93) in the FXLauncher repository (FXLauncher is used for auto-updating and initially downloading all the required files) about the same type of error, which is apparently Mac specific.

**Comment by tiramon** [comment]
I was running it on Win10

**Comment by jmerle** [comment]
Hmm, I don't know exactly why it fails yet, but it's a Java version issue. It indeed doesn't seem to work with 1.8.0_73, but works fine with 1.8.0_151.

I will attempt to fix the issue tomorrow.

**Comment by tiramon** [comment]
works much better with a version that is not 2 years old ;)

**Comment by tiramon** [comment]
also just appeared with
Java(TM) SE Runtime Environment (build 9.0.1+11)

and yes i know it is also not the newest version

**Comment by jmerle** [comment]
Regarding the JAXB error, I opened an issue here: https://github.com/edvin/fxlauncher/issues/100
The second error seemed like an SSL error, so I might be able to fix that one myself. I don't know for sure though, and am pretty busy for the next few days, but it's still on my todo list.

**Comment by tiramon** [comment]
No rush, i currently got a working version, just wanted to inform you

**Comment by jmerle** [comment]
I just removed the dependency on fxlauncher in the develop branch, so this issue won't appear anymore.
