### ISSUE TITLE
App does not start with Win10 1809 / JRE1.8.0_202

### ISSUE THREAD

**Issue by TinoM** [jmerle/cg-local-app#3]
Since today i am no longer able to start the app, even starting directly after a reboot i get:

> "Only one istance of CG local can be running at a time. Please use the running instance."

So, of course some things changed on my system since it was working yesterday which could be a cause:
- Updated JRE from 1.8.0_187 to 1.8.0_202
- Updated Windows 10 with Feature Update 1809

I've checked both the Ports 50005 and 53135 that no other app is listening on them. Running with a Administrative Account does not help, either.

I am not able to install JDK8/Gradle to compile the app myself, are there any other ways to help debugging? Enable verbose logging?

**Comment by jmerle** [comment]
That's odd. I am running JDK 1.8.0_201 myself, so I doubt that is the issue.

I am not a Windows user, but from what I can gather there were quite a few changes to Windows Security in the update you mentioned. Could you try running it with the Windows Firewall disabled?

**Comment by TinoM** [comment]
Thanks for the hint, yes i think this is the cause.
I am not able to disable the firewall (domain restrictions i suspect), and i have already tried to add java.exe / javaw.exe as allowed application.

I wonder: Previously I always got the first time using a new java version the Notification and a UAC elevation request if I want to allow network access in the public/private/domain network area. This is no longer triggered...

Nvm, i will try to figure out the root cause, and update this issue later...

**Comment by TinoM** [comment]
No idea what went wrong. Today i've tried again, got the Firewall UAC dialogs, was able to allow network access and it is running again...

**Comment by kotx** [comment]
Hello, I have the same issue on 1.8.0_261. Doesn't work even with Defender Firewall disabled.
